# Generated by Django 2.1.1 on 2018-10-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_borrowed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
