# Generated by Django 2.1.1 on 2018-10-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_user_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_borrowed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
