# Generated by Django 2.1.1 on 2018-10-26 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permision', models.CharField(choices=[('ADMIN', 'Administrator'), ('NORMAL', 'Normal User')], default='NORMAL', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('n_socio', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('user_permision', models.ForeignKey(default='NORMAL', on_delete=django.db.models.deletion.CASCADE, to='user.Role')),
            ],
        ),
    ]
