# Generated by Django 2.1.1 on 2018-10-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181027_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permision',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('USER', 'User')], default='USER', max_length=10),
        ),
    ]
